# This manifest file defines things that should really only go
# into "official" builds of Fedora CoreOS (such as including `fedora-release-coreos`)
# or are very "opinionated" like disabling SSH passwords by default.

include: fedora-coreos-base.yaml

automatic-version-prefix: "${releasever}.<date:%Y%m%d>.dev"
mutate-os-release: "${releasever}"

# All Fedora CoreOS streams share the same pool for locked files.
lockfile-repos:
  - fedora-coreos-pool

packages:
  - fedora-release-coreos
  - fedora-repos-ostree

# XXX: this is used by coreos-assembler for artifact naming...
rojig:
  license: MIT
  name: fedora-coreos
  summary: Fedora CoreOS base image

remove-from-packages:
  # Drop NetworkManager support for ifcfg files, see also corresponding
  # overlay.d/14NetworkManager-plugins
  - [NetworkManager, /usr/lib64/NetworkManager/.*/libnm-settings-plugin-ifcfg-rh.so]

remove-files:
  # We don't ship man(1) or info(1)
  - usr/share/info
  - usr/share/man
  # Drop text docs too
  - usr/share/doc

# Things we don't expect to ship on the host.  We currently
# have recommends: false so these could only come in via
# hard requirement, in which case the build will fail.
exclude-packages:
  - python
  - python2
  - python2-libs
  - perl
  - nodejs
  - dnf
  - grubby
  - cowsay  # Just in case
  # Let's make sure initscripts doesn't get pulled back in
  # https://github.com/coreos/fedora-coreos-tracker/issues/220#issuecomment-611566254
  - initscripts
  # For (datacenter/cloud oriented) servers, we want to see the details by default.
  # https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/HSMISZ3ETWQ4ETVLWZQJ55ARZT27AAV3/
  - plymouth

# And remove some cruft from grub2
arch-include:
  x86_64: grub2-removals.yaml
  aarch64: grub2-removals.yaml
  ppc64le: grub2-removals.yaml
